version: '3.7'

services:

 registry:
  image: registry
  restart: always
  container_name: registry
  hostname: registry
  volumes:
   - ./registry:/var/lib/registry
  ports:
   - "5005:5005"
  environment:
   - REGISTRY_HTTP_ADDR-0.0.0.0:5005

 jenkins:
  image: jenkins/jenkins_home
  restart: always
  build:
   context: ./config
   dockerfile: Dockerfile
  hostname: jenkins
  user: root
  ports:
   - "8090:8080"
  environment:
   - JAVA_OPTS="-Dhudson.model.DownloadService.noSignatureCheck=true"
   - DOCKER_HOST=unix://var/run/docker.sock
  volumes:
   - "./jenkins_home:/var/jenkins_home"
   - "/var/run/docker.sock:/var/run/docker.sock"
